/*
	see comment in OSGCOMUI.h

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#import <Cocoa/Cocoa.h>
#include <CoreAudio/CoreAudio.h>
#include <AudioUnit/AudioUnit.h>
#include <OpenGL/gl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/param.h>
#include <sys/time.h>

#define EnableDragDrop 1
#define MyAppIsBundle 1
#define WantOSGLUCCO 1

#define kStrAppName "Mini vMac"
#define kAppVariationStr "minivmac-37.03-SE"
#define kStrCopyrightYear "2020"

/* Maintainer information */
#define kMaintainerName "Phil Zakharchenko"
#define kStrHomePage "https://philz.work"

